### Example 3: Matrices

In [11]:
class Matrix:
    def __init__(self, data):
        self.data = data
        
    def __add__(self, other):
        if len(self.data) != len(self.other):
            raise ValueError("Matrices have different dimensions")
        
        for i in range(len(self.data)):
            if len(self.data[i]) != len(self.other[i]):
                raise ValueError("Matrices have different dimensions")
                
        results = []
        for i in range(len(self.data)):
            row = []
            for j in range(len(self.data[i])):
                row.append(self.data[i][j]+self.other[i][j])
            results.append

In [12]:
import numpy as np

In [13]:
a = np.array([[2,3],[1,2]])

In [14]:
a

array([[2, 3],
       [1, 2]])

In [15]:
b = np.array([[-2,5],[7,-1]])

In [16]:
b

array([[-2,  5],
       [ 7, -1]])

In [17]:
m = Matrix(a)

In [18]:
n = Matrix(b)

In [19]:
print(a.__add__(b))

[[0 8]
 [8 1]]
